#!/bin/sh
#
#chkconfig: 345 20 80
#
#description: mw-serve

### BEGIN INIT INFO
# Provides:       mw-serve
# Required-Start: $remote_fs
# Required-Stop:  $remote_fs
# Should-Start:   $network $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
### END INIT INFO


PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

case "$1" in
    start)
        mkdir -p /tmp/mwcache
        chown www-data.www-data /tmp/mwcache
        su - www-data -c 'mw-qserve >> /tmp/mwcache/log.txt 2>&1 &'
        su - www-data -c 'nserve >> /tmp/mwcache/log.txt 2>&1  &'
        su - www-data -c 'nslave --cachedir /tmp/mwcache/ >> /tmp/mwcache/log.txt 2>&1 &'
        su - www-data -c 'postman >> /tmp/mwcache/log.txt 2>&1 &'
    ;;
  stop)
        #mv /data/mwcache/log.txt /data/mwcache/log.old
        killall postman
        killall nslave
        killall nserve
        killall mw-qserve
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/mw-serve {start|stop}"
    exit 1
    ;;
esac

exit 0
